### ISSUE TITLE
Display matching movies from IMDB in EditMovieGUI window.

### ISSUE THREAD

**Issue by trin5tensa** [trin5tensa/moviedb#318]

**Comment by trin5tensa** [comment]
EditMovieGUI and AddMovieGUI are subclassed from the common base class MovieGUI. It is likely that the failure to collect and display TMDB movies is either a minor oversight or a simple code flaw.

**Comment by trin5tensa** [comment]
### TODO

- [x]  Diagnose
- [x] Specify conditions for enabling and disabling the Commit button.
- [x] Specify conditions for calling `MovieGUI.tmdb_search`.
- [x] Move `MovieGUI.call_title_notifees` to `AddMovieGUI`.
- [x] Integration test: Moved code.
- [x] Unittest: Moved code.
- [x] Code Observer class in guiwidgets_2
- [x] Unit test Observer class in guiwidgets_2

***Code***
- [x] Code and  test: AddMovieGUI `Commit` button management.
- [x] Code and  test: AddMovieGUI TMDB lookup.
- [x] Code and  test: Preferences `Commit` button management.
- [x] Code and  test: AddTagGUI `Commit` button management.
- [x] Code and  test: SearchTagGUI `Commit` button management.
- [x] Code and  test: EditTagGUI `Commit` button management.
- [x] Code and  test: EditMovieGUI `Commit` button management excluding 'notes' and 'movie tag' fields.
- [x] Code and  test: EditMovieGUI `Commit` button management with 'notes' field.
- [x] Code and  test: EditMovieGUI `Commit` button management with 'movie tag' field.
- [x] Fix all broken tests
- [x] Replace any remaining traces of the neuron module from guiwidgets_2.py

**Clean up actions**
- [ ] Clear all outstanding todos.
- [ ] Clear code smells.
- [ ] 100% coverage.

### Log
3/20/2024 All broken tests fixed.
3/19/2024 Tests for Add, Search, Edit, and Select Tag completed along with PreferencesGUI. All tag and preference tests moved to new test module.
3/13/2024 Tests for TagGUI completed.
3/8/2024 Tests for new EditMovieGUI completed.
3/5/2024 Tests for new AddMovieGUI completed.
3/2/2024 Tests for new MovieGUI completed.
2/24/2024 A facade for tkinter has been created as patterns.py.
1/29/2024 `entry_fields` were originally envisaged as data structure to manage rows of widgets comprising a label and a user entry.  In the beginning they were used for four ttk.Entry fields. The associated class `_EntryField` became specialized for use with tsk.Entry widgets. When other tk widgets arrived their requirements were handled with special code that was poorly integrated with `_EntryField`. (`ttk.treeview`, `ttk.checkbutton`, `tk.notes`). Each tkinter widget should have had its own subclass.
`guiwidgets_2` has been partially 'cleaned up' ready for extending the `Commit` button management to the movie tags field. This will be committed to provided a clean rollback point. The subclasses will be created and special case code refactored.
1/26/2024 The movie tags treeview was kept completely separate from the entry_fields field management dictionary. As a necessary first step the MOVIE_FIELD_NAMES tuple has been removed to avoid indexing problems. If an `MOVIE_TAGS` were added to that tuple then MOVIE_FIELD_NAMES[-1] would then point to the wrong item.
1/25/2024 Alterations to the notes field are now correctly intercepted using the new prototype method, `_InputZone.text_modified`.  Changes to the `notes` field now correctly enable and disable the `Commit` button.
Also corrected was a bug in the font specification. A tk.Text object should have a default font established by the `font` argument to `tk.Text()` and not via a tag. This was causing appended text to be displayed as `TkDefultFont` and not the desired `TkTextFont`.
1/24/2024 The code was refactored so that text fields created by the `_InputZone.add_text_row` method would be integrated with the entry_fields attribute of `MovieGUI` and not treated as a special case. This was in preparation for using the special case `<<Modified>>` virtual event which is used by `tk.text` instead of `tk.StringVar`.
1/22/2024 Tk's Text widget uses a different method of change notification than other widgets. [Besides the normal low-level events, the text widget generates a `<<Modified>>` virtual event whenever a change is made to the content of the widget, and a `<<Selection>>` virtual event whenever there is a change made to which text is selected.](https://tkdocs.com/tutorial/text.html#bindings)
1/19/2024 There is a bug in `EditMovieGUI.enable_commit_button`. If the user deletes a numeric field in its entirety the subsequent int('') raises a ValueError. As this is part of new code created by this issue #318 no separate issue has been raised.
1/10/2024 A working method for enabling and disabling the commit button has been created. It requires polishing. 
moviedb-#339 has been completely incorporated into this issue.
1/6/2024, 1/8/2024
Notes on current method of handling observed events.
In `MovieGUI` the `entry_fields` dict is initialized with a key of field name and a value of `_EntryField()`.  The `observer` attribute is initialized to `None`. The original_value field is initialized to "".
The `original_values` method of `MovieGUI`'s subclass is called. For `AddMovieGui` this merely overwrites the `original_values` with that same "" value as they already had. For `EditMovieGUI` the values will be those supplied by the caller. These include tag selections. The 'field' is the whole row comprised of a label widget and either an entry widget or a test widget. 

The row addition methods of class _InputZone have been added at different times and are not consistent in their treatment of setting change callbacks or even whether callbacks are set. 
Some attributes of the `_EntryField` object are updated in `_InputZone.add_entry_row` method. The `ttk.Entry` widget is set to the `text_variable` attribute of the entry_field object. The `entry_field.text_variable` is set to the `original_value` which was updated by the `original_values` method.
The `_InputZone.add_text_row` inserts text from `entry_field.original_value` but does not set up any callbacks if the text is changed by the user.
The `_InputZone.add_checkbox_row` does not set up any callbacks if the text is changed by the user. Although it links the checkbutton's `variable` argument to `entry_field.textvariable` it does not set that variable to the `original_value`.
The `_InputZone.add_treeview_row` 
The text row and treeview row return the widget to the caller but entry row and checkbox row do not.  

Should the `_InputZone` methods create an observer and the mechanism for notifying an observer whenever the user changes one of the input zone's widgets? There are only four users of `_InputZone`: `AddMovieGUI`, `EditMovieGUI`, `Preferences`, and `SearchTagGUI`. There is no point in gathering data which may be required by an observer's `notify` method and passing it to the observers notify method as this creates an obsfuscated observer pattern.

1/4/2023 It's become clear that the overall design of event management via the Observer pattern its incoherent.

Each operation within a GUI class such as button enablement or TMDB searches should be controlled by a single function. That function will be responsible for such things as button enablement or invocation of external callbacks. The function will registered by calling the `register` method of every relevant Observer and will be consequently called whenever the `notify` method of any relevant observer is called.

Example for `AddMovieGUI`'s `Commit` button.
The `Commit` button should be enabled if text is present in both title and year fields and disabled otherwise.
Any change to the text of the title field should cause a call to the `notify` method of the title observer. Similarly, changes to the text of the year field should cause a call to the `notify` method of the year observer. The calls to the `notify` method should be made directly without any modification of `tkinter`'s arguments.
A receiving method of AddMovieGUI will receive the notification from either the title observer or the year observer. It is responsible for retrieving the current value of both the title and the year field. If text is present in both then it should enable the `Commit` button otherwise it should disable the `Commit` button.

12/30/2023
**Updated `Commit` button management:**

1. Any change from original field or treeview values should enable the `Commit` button.
2. Each observer calls a common function which checks every widget against its original value. Observers will be triggered by a change in any field.
3. The common function will be called during __post_init__ to set the enablement of the `Commit` button.
4. `MovieGUI.tags_treeview_callback` is called with the user's changes to the list of tags. It places the revised list in the `selected_tags` attribute. If overridden in EditMovieGUI this could be used to detect a change in the tag selection. The original selection is stored at `EditMovieGUI.old_movie['tags']`.

**TMDB search management**

1. Create a method which calls TMDB search with keyboard detection delay.
2. Register the method with the `title` field observer.
3. The method will be called during __post_init__ to populate the TMDB treeview.

12/29/2023 
1. Any change from original field values should enable the `Commit button.
2. A possible design would be a single Observer calling a single function which checks each field against its original value. That single Observer would be triggered by a change in any field.
3. `MovieGUI.tags_treeview_callback` is called with the user's changes to the list of tags. It places the revised list in the `selected_tags` attribute. If overridden in EditMovieGUI this could be used to detect a change in the tag selection. The original selection is stored at `EditMovieGUI.old_movie['tags']`.

12/28/2023 Investigating `MovieGUI.call_title_notifees` to see if it can be used by EditMovieGUI.
12/23/2023 Investigation shows that movies are not being displayed as described in the 8/25/2023 note. 
Although all the code to invoke the TMDB callback is part of the MovieGUI base class it is linked by the subclass. At this time only the AddMovieGUI subclass has the links. The links do not exist in EditMovieGUI.
