### ISSUE TITLE
DB1 Prototype and API

### ISSUE THREAD

**Issue by trin5tensa** [trin5tensa/moviedb#361]
# DB1 Implementation Phase Prototype and API Plan

Create a prototype to explore thoroughness of training for DB1 implementation and identify weaknesses.

This will not include any integration testing or unittesting. Exception handling will be excluded except for prototyping a single general case.

### Prepare the codebase:

- [x] #356: Create new directory environment: Create a database file directory with DB0 and DB1 subdirectories
- [x] #360 Move database python source files to a single directory for database sources.
- [x] #355 Remove old impex.py module

#### Prototype Database

- [x] #366: 
    Create a populated database with complete schema 
    Add prototype code to explore SQLAlchemy v2 patterns for inserting, updating, and deleting.  

#### Database: 

Create new database in default location
Open existing  database from default location
- [x] #369 : Open new and old and update old version.

### API

- [x] Docs: Update API and finalize. Include movie integer.py.
- [x] GIT: Create issues to implement API
- [x] GIT: Create issues to update handlers

### Cutover
The project was split into two: One — DB0 — for production use and one — DB1 — for development.

- [x] #416 Connect `moviedb.start_up()` to database_src.environment.start_engine()
- [x] #466 Relink `main window.MainWindow.place_menubar` to handlers in gui_handlers folder
- [x] #423 Add a call to the close database function (The 'orphan' check)

#### Integration Testing

- [x] Integration testing with empty database
- [x] Integration testing of DB0 -> DB1 database update.
- [x] Issues arising from integration testing.

### Clean up

- [x] #484
- [x] #489
- [x] #473
- [x] #485
- [x] #486
- [x] Delete old modules which used DB0. database.py, handlers.py, utilities.py.
- [x] Delete database.py
- [x] Rename 'database_src' folder to 'database'
- [x] #487
- [x] [Security review.](https://docs.github.com/en/code-security/getting-started/github-security-features)
